### ISSUE TITLE
Command stuck yo starhackit

### ISSUE THREAD

**Issue by mychaelgo** [FredericHeem/generator-starhackit#1]
After run command 

```
yo starhackit
```

console stuck after asking Project Name

**Comment by FredericHeem** [comment]
Thanks for the report, I'll investigate, in the meantime, please clone the starhackit repo from github.

**Comment by FredericHeem** [comment]
After upgrading the dependencies, it seems to work. Likely to be an issue with `inquirer-npm-name` which contacts the npm server to find out of if the project name already exists. 
Do you mind to give a second attempt ?

**Comment by mychaelgo** [comment]
OK it's work now. Thank for support!
