### ISSUE TITLE
no .gitignores included

### ISSUE THREAD

**Issue by rkoberg** [FredericHeem/generator-starhackit#2]
just installed the generator globally and ran `yo starhackit`, but the .gitignores (.gitignore, client/.gitignore, server/.gitignore) are not included.

**Comment by FredericHeem** [comment]
That's weird issue, thanks for the report

**Comment by FredericHeem** [comment]
Here is the explanation: https://github.com/yeoman/generator/issues/812

**Comment by FredericHeem** [comment]
A workaround against npm renaming `.gitignore`  in `.npmignore` has been implemented,  please try the new version 2.0.10

**Comment by rkoberg** [comment]
fixed
